### ISSUE TITLE
run logs in README example are expired

### ISSUE THREAD

**Issue by pxhanus** [peter-evans/docker-compose-actions-workflow#3]
The run logs in README example are expired and therefore not visible. Since it's a big part of the example it would be great if they were at least rerun. To increase resiliency something like screenshotting the most relevant bits and adding them directly to the README might make rerunning less urgent in the future?

**Comment by peter-evans** [comment]
Hi @pxhanus 

Thanks for letting me know. I've updated the link to a fresh run for now and I'll think about how to handle expired runs. A screenshot might be a good idea.

Thanks!
